version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-root}
      MYSQL_DATABASE: ${DB_NAME:-focus_db}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASS:-root}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      # host:container mapping uses an environment variable so you can override
      # at runtime with a free port (example: DB_HOST_PORT=33062 docker compose up -d)
      - "${DB_HOST_PORT:-3002}:5506"

  app:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
    # Allow container to reach the host machine using the special DNS name
    # `host.docker.internal` (mapped to the host gateway). This lets the
    # app container connect to a MySQL instance running on the Docker host.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SERVER_PORT:-4000}:${SERVER_PORT:-4000}"
    depends_on:
      - db
    volumes:
      - uploads:/usr/src/app/uploads

volumes:
  mysql_data:
  uploads:
